:rosa_api_url: {rosa_api_url}

= ROSA FSx Workshop
:numbered:

This lab guide provides a walkthrough on using FSx for ONTAP as a persistent storage layer for applications on *Red Hat OpenShift Service on AWS* (ROSA). It will guide you through the steps to install the NetApp Trident Container Storage Interface (CSI) driver on a ROSA cluster. Additionally, you will learn how to provision an FSx for ONTAP file system, deploy a sample stateful application. To ensure your data’s resilience, you learn how to backup and restore your application data.

NOTE: This lab guide assumes you are using the RHDP environment and are logged into the bastion.


. <<lab-setup,Lab Setup>>
. <<provision-fsx-for-ontap,Provision FSx for ONTAP>>
. <<config-trident,Install and Configure the Trident CSI driver for ROSA>>
. <<csi-backend,Install and Configure the Trident CSI backend to FSx for ONTAP>>
. <<storage-class,Create storage class in ROSA cluster>>
. <<deploy-mysql,Deploy MySQL stateful application>>
. <<creating-snapshots,Creating Snapshots>>
. <<data-recovery,Data Recovery>>
. <<validation,Validate the Database was Restored>>


[[lab-setup]]
== Lab Setup

=== Authenticate `oc` to the cluster

The bastion provided with the RHDP workshop has the `aws` and `rosa` command line tools already installed and logged in.  The `oc` command is installed, but not authenticated.

To authenticate `oc` use the API URL, username, and password provided by the RHDP lab deployment.

Replace the URL and password with your own. Remember this is senstive data, so do not share with anyone.

[source,bash,role=execute,subs="attributes"]
----
oc login {rosa_api_url} -u {rosa_admin_user} -p {rosa_admin_password}
----

=== Git Clone the Lab Repo

Clone the Git repository:

[source,bash]
----
git clone https://github.com/redhat-gpst/rosa-fsx-lab-guide.git rosa-fsx
----

`cd` into the rosa-fsx/fsx directory. This will be the main working directory for the lab.

[source,shell]
----
cd ~/rosa-fsx/fsx
----
